### ISSUE TITLE
ExtractOfftargets uses fixed absolute path "/mnt/ssd1/Crackling-extractOfftargets"

### ISSUE THREAD

**Issue by youngjack86** [bmds-lab/CracklingPlusPlus#2]
Hi there,
I found that the ExtractOfftargets program uses a fixed path "/mnt/ssd1/Crackling-extractOfftargets", which may cause errors on the user machine. See https://github.com/bmds-lab/CracklingPlusPlus/blob/08e167ba4dfa40ad01736cd2ebf0b06d8f906c29/ExtractOfftargets/ExtractOfftargets.cpp#L29
Could you please fix this?
Jack

**Comment by CeSchmitz** [comment]
Hi Jack,

I have addressed the issue in [ 409d710](https://github.com/bmds-lab/CracklingPlusPlus/commit/409d710d867b28ec00fe4f393145d5e0c4f7809b).

Thank you for reaching out.
